version: "3.4"
services:
  reservation-service:
    build: .
    container_name: reservation_service
    volumes:
      - .:/usr/src/app
    command: npm run start
    networks:
      - reservation_network

networks:
  reservation_network:
    external:
      name: reservation_network
